name: Build

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: tf

env:
  TF_VAR_aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
  TF_VAR_aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_git_sha: ${{github.sha}}

jobs:
  # fetch_ecr_repo:
  #   name: Fetch ECR Repository
  #   runs-on: ubuntu-latest
  #   outputs:
  #     ecr_repo: ${{steps.vars.outputs.ecr_repo}}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Lint terraform code (run terraform fmt before commit)
  #       id: fmt
  #       run: terraform fmt -check

  #     - name: Terraform Init
  #       id: init
  #       run: terraform init -backend-config="access_key=${{secrets.AWS_ACCESS_KEY}}" -backend-config="secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}" -backend-config="region=us-west-2" 

  #     - name: Terraform Workspace
  #       id: workspace
  #       run: terraform workspace select beta

  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate -no-color

  #     - name: Terraform Plan
  #       id: plan
  #       run: terraform plan -out .tfplan -no-color

  #     - name: Set vars
  #       id: vars
  #       run: |
  #         printf "ecr_repo=%s\n" $(terraform output -raw ecr_repo) >> "$GITHUB_OUTPUT"

  build_image:
    name: Build docker container
    # needs: fetch_ecr_repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
      #     aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws-region: us-west-2

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: danielhood:${{github.sha}}
          # push: true
          # tags: ${{steps.login-ecr.outputs.registry}}/mapsimum-beta-web:${{github.sha}}
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # apply_terraform:
  #   name: Apply terraform
  #   runs-on: ubuntu-latest
  #   needs: build_and_push_base_image

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Terraform Init
  #       id: init
  #       run: terraform init -backend-config="access_key=${{secrets.AWS_ACCESS_KEY}}" -backend-config="secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}" -backend-config="region=us-west-2" 

  #     - name: Terraform Workspace
  #       id: workspace
  #       run: terraform workspace select beta

  #     - name: Terraform Plan
  #       id: plan
  #       run: terraform plan -out .tfplan -no-color

  #     - name: Terraform Plan
  #       id: apply
  #       run: terraform apply .tfplan -no-color
